services:
  postgres:
    image: postgres:16-alpine
    container_name: hottake-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: HotTakeDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d HotTakeDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    image: muralim23/hottake-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hottake-server
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AzureBlobStorage__ConnectionString=${AZURE_STORAGE_CONNECTION_STRING}
      - AzureBlobStorage__ContainerName=${AZURE_STORAGE_CONTAINER_NAME}
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=HotTakeDb;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JwtSettings__SecretKey=${JWT_SECRET}
      - JwtSettings__Issuer=MyBackendApi
      - JwtSettings__Audience=MyReactFrontend
      - AllowedOrigins__0=http://localhost:3000
      - AllowedOrigins__1=http://localhost:5173
      - AllowedOrigins__2=${MY_ORIGIN}
    ports:
      - "5000:5000"

  client:
    image: muralim23/hottake-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: hottake-client
    restart: unless-stopped
    depends_on:
      - server
    environment:
      - BACKEND_URL=http://server:5000
    ports:
      - "3000:80"

volumes:
  postgres_data:
